package:
  name: py4design
  version: "0.32"

source:
  path: ../
  #git_rev: 0.30
  #git_url: https://github.com/chenkianwee/py4design.git

requirements:
  build:
    - python
    - setuptools
    - pythonocc-core=7.4.0
    - numpy
    - scipy
    - sympy
    - lxml
    - pyshp
    - pycollada
    - networkx
    - cvxopt
    - scikit-learn
    - matplotlib

  run:
    - python
    - pythonocc-core=7.4.0
    - numpy
    - scipy
    - sympy
    - lxml
    - pyshp
    - pycollada
    - networkx
    - cvxopt
    - scikit-learn
    - matplotlib
test:
  imports:
    - py4design

about:
  home: https://github.com/chenkianwee/py4design
  license: GPL3